AllCops:
  Exclude:
    - config.ru
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - out/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
  TargetRubyVersion: 2.3

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyCaseCondition:
  Enabled: false

Semicolon:
  Exclude:
    - spec/**/*

Lambda:
  Enabled: false

RegexpLiteral:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Enabled: false

MultilineBlockChain:
  Enabled: false

inherit_from: .rubocop_todo.yml

